### ISSUE TITLE
[Bug]: Textarea height change causes window to "jump"

### ISSUE THREAD

**Issue by alalpod** [FRSOURCE/autoresize-textarea#132]
### Describe the Bug

Hi :wave: 
Editing long text makes page ( parent element ) scroll jump to the last edited position. The video probably describes it better: https://www.loom.com/share/b0583e8c5f5649b784e288ba5607926e

### Steps to reproduce

- Navigate to docs page https://www.frsource.org/autoresize-textarea/
- Paste long text ( or just use `enter` key to make scrollbar appear )
- Go to several lines up and try to edit text

### Expected behavior

Page ( parent element ) scroll is not affected, like basic textarea.

### Additional context

I tried to investigate it a bit and found out that [this line](https://github.com/FRSOURCE/autoresize-textarea/blob/main/src/index.ts#L14) is responsible for the behavior. Removing it fixes the bug, but it breaks shrinking behavior.

### Package version

1.3.89

### Device

PC

### OS and version

All

### Browser and version

Chrome, FF

### Node version

18

### I can work on it by myself

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FRSgit** [comment]
Hey @alalpod!
Long time no see 😄 
Thanks for the video & detailed report - I'll have a look at this week

**Comment by alalpod** [comment]
@FRSgit Hey, thanks a lot for quick fix, works like a charm! :tada:
